services:
 mongo-review:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_review_data:/data/db
 mongo-image:
  image: mongo:latest
  ports:
    - 27018:27017
  volumes:
    - mongodb_review_data:/data/db
    
 mysql-user:
  image: mysql:latest
  ports:
    - 3308:3306
  volumes:
    - mysql_user_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-restaurant:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_restaurant_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 review-service:
  depends_on:
    - mongo-review
  image: ./review-service
  ports:
    - 8082:8082
  links:
    - mongo-review
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-review
   
 image-service:
  depends_on:
    - mongo-image
  image: ./image-service
  ports:
    - 8084:8084
  links:
    - mongo-image
  environment:
   MONGODB_PORT: 27018
   MONGODB_HOST: mongo-image

 user-service:
  depends_on:
    - mysql-user
  image: ./user-service
  ports:
    - 8083:8083
  links:
    - mysql-user
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-user
   MYSQL_DB_PORT: 3308

 restaurant-service:
  depends_on:
    - mysql-restaurant
  image: ./restaurant-service
  ports:
    - 8081:8081
  links:
    - image-service
    - review-service
  environment:
   REVIEW_SERVICE_BASEURL: review-service:8082
   IMAGE_SERVICE_BASEURL: image-service:8084
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-restaurant
   MYSQL_DB_PORT: 3307

volumes:
 mongodb_review_data:
 mongodb_image_data:
 mysql_restaurant_data:
 mysql_user_data: