version: '3'

services:
  mongo-review:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_review_data:/data/db

  mongo-image:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongodb_image_data:/data/db

  mysql-user:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - mysql_user_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mysql-restaurant:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_restaurant_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  review-service:
    depends_on:
      - mongo-review
    image: joppevhd/review-service
    ports:
      - 8082:8082
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-review

  image-service:
    depends_on:
      - mongo-image
    image: joppevhd/image-service
    ports:
      - 8084:8084
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-image

  user-service:
    depends_on:
      - mysql-user
    image: joppevhd/user-service
    ports:
      - 8083:8083
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-user
      MYSQL_DB_PORT: 3306

  restaurant-service:
    depends_on:
      - mysql-restaurant
      - image-service
      - review-service
    image: joppevhd/restaurant-service
    ports:
      - 8081:8081
    environment:
      REVIEW_SERVICE_BASEURL: review-service:8082
      IMAGE_SERVICE_BASEURL: image-service:8084
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-restaurant
      MYSQL_DB_PORT: 3306

  api-gateway:
    depends_on:
      - review-service
      - user-service
      - restaurant-service
      - image-service
    image: joppevhd/api-gateway
    ports:
      - 8085:8085
    links:
      - review-service
      - user-service
      - restaurant-service
      - image-service
    environment:
      REVIEW_SERVICE_BASEURL: review-service:8082
      USER_SERVICE_BASEURL: user-service:8083
      RESTAURANT_SERVICE_BASEURL: restaurant-service:8081
      IMAGE_SERVICE_BASEURL: image-service:8084

volumes:
  mongodb_review_data:
  mongodb_image_data:
  mysql_restaurant_data:
  mysql_user_data: